apiVersion: batch/v1
kind: Job
metadata:
  name: pft-db-migrate
  namespace: pft
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: pratiteep/pft-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: pft-secrets
          env:
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          command: ["sh","-c"]
          args:
            - alembic upgrade head