FROM python:3.12.3-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY frontend-requirements.txt .
RUN pip install --upgrade pip setuptools wheel && \
    pip install -r frontend-requirements.txt

RUN apt-get purge -y --auto-remove build-essential && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/app
COPY frontend/ ./frontend/

EXPOSE 8501

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]